//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_ticaret_Projemiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siparisler
    {
        public int uyeid { get; set; }
        public int urunid { get; set; }
        public short adet { get; set; }
        public System.DateTime sip_tarihi { get; set; }
        public int sipno { get; set; }
        public long kayitno { get; set; }
    
        public virtual urunler urunler { get; set; }
        public virtual uyeler uyeler { get; set; }
    }
}
